// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform. '
          'Only iOS and Android are supported.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPlf8w9jJTFdhAfAmvULR7JZcGP1HDfw8',
    appId: '1:378901243002:android:d178010a90a0e7d4acc7c3',
    messagingSenderId: '378901243002',
    projectId: 'eventease-70a25',
    databaseURL: 'https://eventease-70a25-default-rtdb.firebaseio.com',
    storageBucket: 'eventease-70a25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv-w0Dp6bWKPx7VGoY48yxTAPuYJxpRZ4',
    appId: '1:378901243002:ios:c94dd3c512fdac69acc7c3',
    messagingSenderId: '378901243002',
    projectId: 'eventease-70a25',
    databaseURL: 'https://eventease-70a25-default-rtdb.firebaseio.com',
    storageBucket: 'eventease-70a25.firebasestorage.app',
    iosClientId:
        '378901243002-qsdd0nmb18nclg66oc3i0v06t1a424lt.apps.googleusercontent.com',
    iosBundleId: 'com.eventease.app',
  );
}
